default: &default
  adapter: postgresql
  encoding: unicode
  username: zoneconvert
  password: password
  pool: 5
development:
  <<: *default
  database: zoneconvert_development
test:
  <<: *default
  database: zoneconvert_test
  username: zoneconvert
  password: password
production:
  <<: *default
  database: zoneconvert_production
  username: zoneconvert
  password: <%= ENV['ZONECONVERT_DATABASE_PASSWORD'] %>
